FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir flask flask-socketio paho-mqtt websocket-client eventlet requests

COPY app.py .

EXPOSE 5050
CMD ["python", "app.py"]
